language: python

python:
  - '3.7'

cache: pip

script:
  # Install project dependencies
  - pip install -r requirements.txt
  # Sphinx build
  - make clean
  - make html
  - touch _build/html/.nojekyll
  - diff -x "CNAME" -r _build/html docs
