language: python

python:
  - '3.7'

cache: pip


#branches:
# only:
#   - master

script:
  - pip install -r requirements.txt
  - make clean
  - make html
  - cp -R _build/html/* docs/
  - echo "Done"

 deploy:
  - provider: pages
  - skip_cleanup: true
  - github_token: $GITHUB_TOKEN
  - keep_history: true
  - local_dir: docs/
  on:
    branch: master
