language: python

python:
  - '3.7'

cache: pip

branches:
  only:
    - master

before_script:
  - echo "before_script"

install: pip install -r requirements.txt

script:
  - make clean
  - make html
  - cp -R _build/html/* docs/
  - echo "Wouhou! New build moved to docs!"
  - git add .
  - git commit -m "Documentation Update $(date -u +"%Y-%m-%d %H:%M")"
  - git push
  - echo "New build pushed"

after_script:
  - echo "after_script"