language: python

python:
  - '3.7'

cache: pip

# deploy:
#   provider: pages
#   skip_cleanup: true
#   github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
#   keep_history: true
#   on:
#     branch: master

branches:
  only:
    - master

script:
  - pip install -r requirements.txt
  - make clean
  - make html
  - cp -R _build/html/* docs/
  - echo "Done"

after_script:
  - git config --global user.email "travis@travis-ci.org"
  - git config --global user.name "Travis CI"
  - git status
  - git add .
  - git commit --message "[travis] Documentation Update $(date -u +"%Y-%m-%d %H:%M")"
  # - git push --set-upstream origin master
  - git push https://${GH_TOKEN}@github.com/SubstraFoundation/substra-documentation.git HEAD:master
