name: Sphinx Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install requirements
        run: pip install -r requirements.txt
      - name: Sphinx make
        run: make clean && make html
      - name: Add nojekyll
        run: touch _build/html/.nojekyll
      - name: Check the diff
        run: diff -x "CNAME" -x "_build/html/.buildinfo" -r _build/html docs

